/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package appinventarisaset;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author UNKNOWN'PC
 */
public class formInventaris extends javax.swing.JFrame {
    
    DefaultTableModel model;
    DefaultTableModel modelKedua;

    /** Creates new form formInventaris */
    public formInventaris() throws SQLException {
        initComponents();
        setLocationRelativeTo(this);
    }
    
    
    private void reset (){
        kodeAset.setText("");
        namaAset.setText("");
        tanggalMasuk.setText("");
        tanggalKeluar.setText("");
        jumlah.setText("");
        kategori.setSelectedItem("");
    }
    
    
    private void kategori (){
        kategori.addItem("Layak");
        kategori.addItem("Kurang Layak");
        kategori.addItem("Rusak");
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kodeAset = new javax.swing.JTextField();
        namaAset = new javax.swing.JTextField();
        tanggalMasuk = new javax.swing.JTextField();
        tanggalKeluar = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        kategori = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bAsetMasuk = new javax.swing.JButton();
        bHapusAsetMasuk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAsetMasuk = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        bAsetKeluar = new javax.swing.JButton();
        bHapusAsetKeluar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAsetKeluar = new javax.swing.JTable();
        jTextField6 = new javax.swing.JTextField();
        bEditAsetMasuk = new javax.swing.JButton();
        bEditKeluar = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        bCetakMasuk = new javax.swing.JButton();
        bCetakKeluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Aplikasi Inventaris Aset");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Kategori");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Kode Aset");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nama Aset");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Tanggal Masuk");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Tanggal Keluar");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Jumlah");

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Layak", "Kurang Layak", "Rusak" }));
        kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 153, 51));

        jLabel14.setBackground(new java.awt.Color(204, 255, 204));
        jLabel14.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("TAMBAH ASET");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tanggalKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaAset, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kodeAset, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jumlah)
                                    .addComponent(kategori, 0, 200, Short.MAX_VALUE))))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kodeAset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaAset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tanggalKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("ASET MASUK");

        bAsetMasuk.setBackground(new java.awt.Color(51, 204, 0));
        bAsetMasuk.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bAsetMasuk.setForeground(new java.awt.Color(255, 255, 255));
        bAsetMasuk.setText("Tambah Aset Masuk");
        bAsetMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAsetMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAsetMasukActionPerformed(evt);
            }
        });

        bHapusAsetMasuk.setBackground(new java.awt.Color(255, 51, 51));
        bHapusAsetMasuk.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bHapusAsetMasuk.setForeground(new java.awt.Color(255, 255, 255));
        bHapusAsetMasuk.setText("Hapus");
        bHapusAsetMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bHapusAsetMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusAsetMasukActionPerformed(evt);
            }
        });

        tAsetMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Jumlah", "Tanggal Masuk", "Kategori"
            }
        ));
        tAsetMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tAsetMasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tAsetMasuk);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("ASET KELUAR");

        bAsetKeluar.setBackground(new java.awt.Color(51, 204, 0));
        bAsetKeluar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bAsetKeluar.setForeground(new java.awt.Color(255, 255, 255));
        bAsetKeluar.setText("Tambah Aset Keluar");
        bAsetKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAsetKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAsetKeluarActionPerformed(evt);
            }
        });

        bHapusAsetKeluar.setBackground(new java.awt.Color(255, 51, 51));
        bHapusAsetKeluar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bHapusAsetKeluar.setForeground(new java.awt.Color(255, 255, 255));
        bHapusAsetKeluar.setText("Hapus");
        bHapusAsetKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bHapusAsetKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusAsetKeluarActionPerformed(evt);
            }
        });

        tAsetKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Jumlah", "Tanggal Masuk", "Tanggal Keluar", "Kategori"
            }
        ));
        tAsetKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tAsetKeluarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tAsetKeluar);

        jTextField6.setBackground(new java.awt.Color(153, 255, 255));
        jTextField6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        bEditAsetMasuk.setBackground(new java.awt.Color(255, 102, 0));
        bEditAsetMasuk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bEditAsetMasuk.setForeground(new java.awt.Color(255, 255, 255));
        bEditAsetMasuk.setText("Edit");
        bEditAsetMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEditAsetMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditAsetMasukActionPerformed(evt);
            }
        });

        bEditKeluar.setBackground(new java.awt.Color(255, 153, 0));
        bEditKeluar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bEditKeluar.setForeground(new java.awt.Color(255, 255, 255));
        bEditKeluar.setText("Edit");
        bEditKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEditKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditKeluarActionPerformed(evt);
            }
        });

        jTextField7.setBackground(new java.awt.Color(255, 204, 204));
        jTextField7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });

        bCetakMasuk.setBackground(new java.awt.Color(51, 51, 255));
        bCetakMasuk.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bCetakMasuk.setForeground(new java.awt.Color(255, 255, 255));
        bCetakMasuk.setText("Cetak");
        bCetakMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCetakMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCetakMasukActionPerformed(evt);
            }
        });

        bCetakKeluar.setBackground(new java.awt.Color(51, 51, 255));
        bCetakKeluar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bCetakKeluar.setForeground(new java.awt.Color(255, 255, 255));
        bCetakKeluar.setText("Cetak");
        bCetakKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCetakKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCetakKeluarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Inventaris Aset");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jButton9.setBackground(new java.awt.Color(255, 0, 0));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Keluar");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("2010010215");

        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Muhammad Rafii Hamdi");

        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("5a non reguler bANJARMASIN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabel11)))
                            .addGap(30, 30, 30))
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap(67, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jLabel11)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel12)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel13)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bEditKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bAsetKeluar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bHapusAsetKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bCetakKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bEditAsetMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bCetakMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(33, 33, 33)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(bAsetMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bHapusAsetMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAsetMasuk)
                    .addComponent(bHapusAsetMasuk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bCetakMasuk)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bAsetKeluar)
                            .addComponent(bHapusAsetKeluar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bEditKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bCetakKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bEditAsetMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jumlahActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void bHapusAsetMasukActionPerformed(ActionEvent evt) {//GEN-FIRST:event_bHapusAsetMasukActionPerformed
        // TODO add your handling code here:
        int i = tAsetMasuk.getSelectedRow();
        
            if(i>=0){
                int pilihan = JOptionPane.showConfirmDialog(
                        null,
                        "Apakah Anda Yakin Ingin Menghapus Data?",
                        "Konfirmasi Hapus",
                        JOptionPane.YES_NO_OPTION);
                if(pilihan==0){
                    try{
                        TableModel model = tAsetMasuk.getModel();
                        DBConnection koneksi = new DBConnection();
                        Connection con = koneksi.getConnection();
                        String executeQuery = "DELETE FROM aset_masuk WHERE kode_aset =?";
                        PreparedStatement ps = con.prepareStatement(executeQuery);
                        ps.setString(1, model.getValueAt(i, 0).toString());
                        ps.executeUpdate();
                    } catch(SQLException ex) {
                        System.out.println("Error Hapus Data Aset Masuk : " + ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Pilih Data yang Ingin Dihapus");
                }
        }
        resetTableMasuk("");
    }//GEN-LAST:event_bHapusAsetMasukActionPerformed

    private void bHapusAsetKeluarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_bHapusAsetKeluarActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        int i = tAsetKeluar.getSelectedRow();
        
            if(i>=0){
                int pilihan = JOptionPane.showConfirmDialog(
                        null,
                        "Apakah Anda Yakin Ingin Menghapus Data?",
                        "Konfirmasi Hapus",
                        JOptionPane.YES_NO_OPTION);
                if(pilihan==0){
                    try{
                        TableModel model = tAsetKeluar.getModel();
                        DBConnection koneksi = new DBConnection();
                        Connection con = koneksi.getConnection();
                        String executeQuery = "DELETE FROM aset_keluar WHERE kode_aset =?";
                        PreparedStatement ps = con.prepareStatement(executeQuery);
                        ps.setString(1, model.getValueAt(i, 0).toString());
                        ps.executeUpdate();
                    } catch(SQLException ex) {
                        System.out.println("Error Hapus Data Aset Keluar : " + ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Pilih Data yang Ingin Dihapus");
                }
        }
        resetTableMasuk("");

    }//GEN-LAST:event_bHapusAsetKeluarActionPerformed

    private void jButton9ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tAsetMasukMouseClicked(MouseEvent evt) {//GEN-FIRST:event_tAsetMasukMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tAsetMasukMouseClicked

    private void kategoriActionPerformed(ActionEvent evt) {//GEN-FIRST:event_kategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriActionPerformed

    private void tAsetKeluarMouseClicked(MouseEvent evt) {//GEN-FIRST:event_tAsetKeluarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tAsetKeluarMouseClicked

    // Method untuk Mengambil Data dari Database, tabel aset_masuk, disimpan ke instance AsetMasuk
     public ArrayList<AsetMasuk> getAsetMasukList(String keyword){
        ArrayList<AsetMasuk> asetMasukList = new ArrayList<AsetMasuk>();
        DBConnection koneksi = new DBConnection();
        Connection connection =koneksi.getConnection();
        AsetMasuk asetMasuk;
        
        String query = "SELECT * FROM aset_masuk " + keyword;
        Statement st;
        ResultSet rs;
        
        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            while(rs.next()){
                asetMasuk = new AsetMasuk(
                        rs.getInt("kode_aset"),
                        rs.getString("nama_aset"),
                        rs.getInt("jumlah"),
                        rs.getString("tanggal_masuk"),
                        rs.getString("kategori"));
                asetMasukList.add(asetMasuk);
            }
        } catch(SQLException | NullPointerException ex) {
            System.err.println("Koneksi Null Gagal");
        }
        return asetMasukList;
    }
    
    
    // Method untuk Menampilkan Data yang Diambil dari method getAsetMasukList ke tAsetMasuk yang ada di Program
    public void selectAsetMasuk(String keyword){
        ArrayList<AsetMasuk> list = getAsetMasukList(keyword);
        DefaultTableModel model = (DefaultTableModel)tAsetMasuk.getModel();
        Object[] row = new Object[5];// 5 karena ada 5 field (kolom)
        
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getKode();     // 0  ->   Field Ke-1
            row[1] = list.get(i).getNama();
            row[2] = list.get(i).getJumlah();
            row[3] = list.get(i).getTanggal();
            row[4] = list.get(i).getKategori();
            
            model.addRow(row);
        }
    }
    
    // Method untuk me-Refresh Tampilan Table
    // Reset Table Aset Masuk
    public final void resetTableMasuk(String keyword){
        DefaultTableModel model = (DefaultTableModel)tAsetMasuk.getModel();
        model.setRowCount(0);
        selectAsetMasuk(keyword);
    }
    
    // Method untuk Menambahkan Data ke aset_masuk
    private void bAsetMasukActionPerformed(ActionEvent evt) {//GEN-FIRST:event_bAsetMasukActionPerformed
        // TODO add your handling code here:
        AsetMasuk asetMasuk = new AsetMasuk();
        asetMasuk.setNama(namaAset.getText());
        asetMasuk.setJumlah(Integer.parseInt(jumlah.getText()));
        asetMasuk.setTanggal(tanggalMasuk.getText());
        asetMasuk.setKategori(kategori.getSelectedItem().toString());
        
        if(asetMasuk.getNama().equalsIgnoreCase("") ||
           asetMasuk.getJumlah()==0 ||
           asetMasuk.getTanggal().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Lengkapi Data");
        } else {
            DBConnection koneksi = new DBConnection();
            Connection con = koneksi.getConnection();
            PreparedStatement ps;
            
            try {
                String qry = "INSERT INTO aset_masuk VALUES (NULL,?,?,?,?)";
                ps = con.prepareStatement(qry);
                ps.setString(1, asetMasuk.getNama());
                ps.setInt(2, asetMasuk.getJumlah());
                ps.setString(3, asetMasuk.getTanggal());
                ps.setString(4, asetMasuk.getKategori());
                ps.executeUpdate();
                System.out.println("Data Aset Masuk Berhasil Ditambahkan");
                resetTableMasuk("");
            } catch (Exception e) {
                System.out.println("Error Tombol Tambah Aset Masuk : " + e);
            }
        }
    }//GEN-LAST:event_bAsetMasukActionPerformed

    private void bAsetKeluarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_bAsetKeluarActionPerformed
        // TODO add your handling code here:        // TODO add your handling code here:
        AsetKeluar asetKeluar = new AsetKeluar();
        asetKeluar.setNama(namaAset.getText());
        asetKeluar.setJumlah(Integer.parseInt(jumlah.getText()));
        asetKeluar.setTanggal(tanggalMasuk.getText());
        asetKeluar.setTanggal2(tanggalKeluar.getText());
        asetKeluar.setKategori(kategori.getSelectedItem().toString());
        
        if(asetKeluar.getNama().equalsIgnoreCase("") ||
           asetKeluar.getJumlah()==0 ||
           asetKeluar.getTanggal().equalsIgnoreCase("")||
           asetKeluar.getTanggal2().equalsIgnoreCase("")     )
        {
            JOptionPane.showMessageDialog(null, "Lengkapi Data");
        } else {
            DBConnection koneksi = new DBConnection();
            Connection con = koneksi.getConnection();
            PreparedStatement ps;
            
            try {
                String qry = "INSERT INTO aset_keluar VALUES (NULL,?,?,?,?,?)";
                ps = con.prepareStatement(qry);
                ps.setString(1, asetKeluar.getNama());
                ps.setInt(2, asetKeluar.getJumlah());
                ps.setString(3, asetKeluar.getTanggal());
                ps.setString(4, asetKeluar.getTanggal2());
                ps.setString(5, asetKeluar.getKategori());
                ps.executeUpdate();
                System.out.println("Data Aset Keluar Berhasil Ditambahkan");
                resetTableKeluar("");
            } catch (Exception e) {
                System.out.println("Error Tombol Tambah Aset Keluar : " + e);
            }
        }
    }//GEN-LAST:event_bAsetKeluarActionPerformed

    public final void resetTableKeluar(String keyword){
        DefaultTableModel model = (DefaultTableModel)tAsetKeluar.getModel();
        model.setRowCount(0);
        selectAsetKeluar(keyword);
    }
    
    public void selectAsetKeluar(String keyword){
        ArrayList<AsetKeluar> list = getAsetKeluarList(keyword);
        DefaultTableModel model = (DefaultTableModel)tAsetKeluar.getModel();
        Object[] row = new Object[6];// 5 karena ada 5 field (kolom)
        
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getKode();     // 0  ->   Field Ke-1
            row[1] = list.get(i).getNama();
            row[2] = list.get(i).getJumlah();
            row[3] = list.get(i).getTanggal();
            row[4] = list.get(i).getTanggal2();
            row[5] = list.get(i).getKategori();
            
            model.addRow(row);
        }
    }
    

     public ArrayList<AsetKeluar> getAsetKeluarList(String keyword){
        ArrayList<AsetKeluar> asetKeluarList = new ArrayList<AsetKeluar>();
        DBConnection koneksi = new DBConnection();
        Connection connection =koneksi.getConnection();
        AsetKeluar asetKeluar;
        
        String query = "SELECT * FROM aset_keluar " + keyword;
        Statement st;
        ResultSet rs;
        
        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            while(rs.next()){
                asetKeluar = new AsetKeluar(
                        rs.getInt("kode_aset"),
                        rs.getString("nama_aset"),
                        rs.getInt("jumlah"),
                        rs.getString("tanggal_masuk"),
                        rs.getString("tanggal_keluar"),
                        rs.getString("kategori"));
                asetKeluarList.add(asetKeluar);
            }
        } catch(SQLException | NullPointerException ex) {
            System.err.println("Koneksi Null Gagal");
        }
        return asetKeluarList;
    }
    
    
    private void formWindowActivated(WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        resetTableMasuk("");
        resetTableKeluar("");
    }//GEN-LAST:event_formWindowActivated

    private void bEditAsetMasukActionPerformed(ActionEvent evt) {//GEN-FIRST:event_bEditAsetMasukActionPerformed
        // TODO add your handling code here:
        int i = tAsetMasuk.getSelectedRow();
        if(i>=0){
            TableModel model = tAsetMasuk.getModel();
            AsetMasuk asetMasuk = new AsetMasuk();
            asetMasuk.setKode(Integer.parseInt(model.getValueAt(i, 0).toString()));
            asetMasuk.setNama(model.getValueAt(i, 1).toString());
            asetMasuk.setJumlah(Integer.parseInt(model.getValueAt(i, 2).toString()));
            asetMasuk.setTanggal(model.getValueAt(i, 3).toString());
            asetMasuk.setKategori(model.getValueAt(i, 4).toString());
            EditAsetMasuk asetMasukEditFrame = new EditAsetMasuk(asetMasuk, this);
            asetMasukEditFrame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Pilih Data yang Ingin Diedit");
        }
    }//GEN-LAST:event_bEditAsetMasukActionPerformed

    private void bEditKeluarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_bEditKeluarActionPerformed
        // TODO add your handling code here:
                int i = tAsetKeluar.getSelectedRow();
        if(i>=0){
            TableModel model = tAsetKeluar.getModel();
            AsetKeluar asetKeluar = new AsetKeluar();
            asetKeluar.setKode(Integer.parseInt(model.getValueAt(i, 0).toString()));
            asetKeluar.setNama(model.getValueAt(i, 1).toString());
            asetKeluar.setJumlah(Integer.parseInt(model.getValueAt(i, 2).toString()));
            asetKeluar.setTanggal(model.getValueAt(i, 3).toString());
            asetKeluar.setTanggal2(model.getValueAt(i, 4).toString());
            asetKeluar.setKategori(model.getValueAt(i, 5).toString());
            EditAsetKeluar asetKeluarEditFrame = new EditAsetKeluar(asetKeluar, this);
            asetKeluarEditFrame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Pilih Data yang Ingin Diedit");
        }
    }//GEN-LAST:event_bEditKeluarActionPerformed

    private void jTextField6ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField6KeyReleased(KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        // TODO add your handling code here:
        try{
            DBConnection koneksi = new DBConnection();
            Connection con = koneksi.getConnection();
        
            DefaultTableModel model = (DefaultTableModel)tAsetMasuk.getModel();
            model.setRowCount(0);
            PreparedStatement ps = con.prepareStatement("Select * From aset_masuk where nama_aset LIKE" + "'%"+ jTextField6.getText().trim()+"%'" );
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
                int kode = rs.getInt("kode_aset");
                String nama = rs.getString("nama_aset");
                int jumlah = rs.getInt("jumlah");
                String tanggal = rs.getString("tanggal_masuk");
                String kategori = rs.getString("kategori");
                model.addRow(new Object[]{kode, nama, jumlah, tanggal, kategori});
            }
            rs.close();
            ps.close();
        } catch (Exception e){
            System.out.println("Koneksi Gagal pada Pencarian Nama Aset Masuk()");
        }
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jTextField7KeyReleased(KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        // TODO add your handling code here:
                try{
            DBConnection koneksi = new DBConnection();
            Connection con = koneksi.getConnection();
        
            DefaultTableModel model = (DefaultTableModel)tAsetKeluar.getModel();
            model.setRowCount(0);
            PreparedStatement ps = con.prepareStatement("Select * From aset_keluar where nama_aset LIKE" + "'%"+ jTextField7.getText().trim()+"%'" );
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
                int kode = rs.getInt("kode_aset");
                String nama = rs.getString("nama_aset");
                int jumlah = rs.getInt("jumlah");
                String tanggal = rs.getString("tanggal_masuk");
                String tanggal2 = rs.getString("tanggal_keluar");
                String kategori = rs.getString("kategori");
                model.addRow(new Object[]{kode, nama, jumlah, tanggal, tanggal2, kategori});
            }
            rs.close();
            ps.close();
        } catch (Exception e){
            System.out.println("Koneksi Gagal pada Pencarian Nama Aset Keluar()");
        }

    }//GEN-LAST:event_jTextField7KeyReleased

    private void bCetakMasukActionPerformed(ActionEvent evt) {//GEN-FIRST:event_bCetakMasukActionPerformed
        // TODO add your handling code here:
        File reportAsetMasuk = new File(".");
        String direktori = "";
        
        DBConnection koneksi = new DBConnection();
        Connection con = koneksi.getConnection();
        String query = "SELECT * FROM aset_masuk";
        
        
        try {
            Statement stat = con.createStatement();
            direktori = reportAsetMasuk.getCanonicalPath() + "/src/appinventarisaset/report/";
            JasperDesign desain = JRXmlLoader.load(direktori + "reportMasuk.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(desain);
            ResultSet rs = stat.executeQuery(query);
            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap(), rsDataSource);
            JasperViewer.viewReport(jp);
        } catch (SQLException | IOException | JRException ex) {
            System.out.println("Gagal Mencetak Laporan Aset Masuk : " + ex);
        }
    }//GEN-LAST:event_bCetakMasukActionPerformed

    private void bCetakKeluarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_bCetakKeluarActionPerformed
        // TODO add your handling code here:
        File reportAsetKeluar = new File(".");
        String direktori = "";
        
        DBConnection koneksi = new DBConnection();
        Connection con = koneksi.getConnection();
        String query = "SELECT * FROM aset_keluar";
        
        
        try {
            Statement stat = con.createStatement();
            direktori = reportAsetKeluar.getCanonicalPath() + "/src/appinventarisaset/report/";
            JasperDesign desain = JRXmlLoader.load(direktori + "reportKeluar.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(desain);
            ResultSet rs = stat.executeQuery(query);
            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap(), rsDataSource);
            JasperViewer.viewReport(jp);
        } catch (SQLException | IOException | JRException ex) {
            System.out.println("Gagal Mencetak Laporan Aset Keluar : " + ex);
        } 
    }//GEN-LAST:event_bCetakKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formInventaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formInventaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formInventaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formInventaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new formInventaris().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(formInventaris.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAsetKeluar;
    private javax.swing.JButton bAsetMasuk;
    private javax.swing.JButton bCetakKeluar;
    private javax.swing.JButton bCetakMasuk;
    private javax.swing.JButton bEditAsetMasuk;
    private javax.swing.JButton bEditKeluar;
    private javax.swing.JButton bHapusAsetKeluar;
    private javax.swing.JButton bHapusAsetMasuk;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jumlah;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JTextField kodeAset;
    private javax.swing.JTextField namaAset;
    private javax.swing.JTable tAsetKeluar;
    private javax.swing.JTable tAsetMasuk;
    private javax.swing.JTextField tanggalKeluar;
    private javax.swing.JTextField tanggalMasuk;
    // End of variables declaration//GEN-END:variables

}
